### ISSUE TITLE
Base technical components epic

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#1]
Here is a first pass at the base technical components we will want to get going

- [x] have a drupal instance that runs in cloud.gov (That's this!)
- [x] have it dockerized for local development [pull 7 in the example repo](https://github.com/18F/cf-ex-drupal8/pull/7)
- [ ] have configurations configurable for production [in progress](https://github.com/18F/cf-ex-drupal8/pull/19)
- [ ] have data connection from this portal to DOJ
- [ ] create webform
- [ ] set up ci/cd 
- [ ] configure email
- [ ] integrate single sign on with DOJ
- [x] create cloud.gov prototyping account

(Big thanks to Fureigh and Peter, for getting the first two done!)

Followed by:
 - styling
 - workflows
