### ISSUE TITLE
Mobile front end fixes (from last design audit, week of June 8-12)

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#608]
# Backround:
These issues were collected by myself and @Jacklynn the week of June 8-12th, after the work @hbillings did on the design/dev overhaul, and after the release that week.

# Tasks
### @cantsin @Jkrzy please check these off once you've completed them so we can keep track of what's been done or not moving forward. _(Full explanation of issues below)_

- [ ] **1:** DOJ name in Header area
- [ ] **2:** 911 line break issue
- [ ] **3:** Examples dropdown: 
- **A:** Extra padding
-  **B:** Dropdown arrow misaligned
- [ ] **4:** Protected characteristics list padding
- [ ] **5:** FORM - Contact page: State and zipcode overlapping
- [ ] **6:** FORM - Primary Concern cards: Grey line missing
- [ ] **7:** FORM - Location Details: Second line of radio buttons still has weird indent (see "Place of worship")
- [ ] **8:** FORM - Personal Characteristics: Spacing between header and question
- [ ] **9:** Review page: 
- **Spacing:** in cards
- **Edit buttons** too wide
- [ ] **10:** Privacy Policy footer: column to narrow
- [ ] **11:** Confirmation page: issues within confirmation card

# Details

## 1. DOJ name in Header area
- I see we tried to fix the menu running into the agency name issue, but now it’s stacked below the logo—can we just make the type of the name smaller so it fits next to it? Is it possible to scale so if the screen is smaller the text gets smaller? (SUGGESTION: 8px for "U.S. Department of Justice" and 14px for "Civil Rights Division"
![Screen Shot 2020-06-23 at 3.41.36 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c8dc5b9c-985b-40d9-9c48-c9f5890b97ed)

## 2. 911 header is still going to two lines
Can we just make it 911 instead of 9-1-1 so at least the numbers will stay together? OR make the header not be as wide so more of it goes to the second line
![Screen Shot 2020-06-23 at 3.43.23 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/a86252bd-07dd-4fe1-ad1e-d1ddab087b01)

## 3. Examples dropdown
**A.** The examples text in the white box doesn’t need to retain the extra padding inside on mobile, it can just use the full space with 24 px padding like the other cards

**Current**
![Screen Shot 2020-06-23 at 3.47.05 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/94f82cdc-5052-492e-9378-3ed7fc339ba9)

**Mockup**
(text only needs the 24px padding within the card, doesn’t need more, doesn’t utilize the space well at that size)
![Screen Shot 2020-06-23 at 3.49.34 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/42a7c8d0-f46c-4753-b52b-e5d9f26ab2d0)

**B.** Dropdown arrow should always align with the top line of text, not the middle
![Screen Shot 2020-06-23 at 3.55.19 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c006d15b-5203-4c85-92c4-f2062f115d54)

## 4. Protected characteristics list 
Same as the examples dropdown, the list doesn’t need to be indented, should utilize the full width of the columns
![Screen Shot 2020-06-23 at 3.59.27 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/69910be0-fb2d-427a-89b0-28bf964a0406)

## 5. FORM - Contact page
State and zipcode are overlapping
![Screen Shot 2020-06-23 at 4.04.15 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/4e36ca69-da74-496d-be7a-ae8f14282619)

## 6. FORM - Primary Concern cards 
Need grey line between header + “Examples”
_We discussed in slack [here](https://gsa-tts.slack.com/archives/G014URTPB7U/p1591648203015400)_
![Screen Shot 2020-06-23 at 4.08.23 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/277041f0-fa89-4407-b342-eb1da7d12763)

## 7. FORM - Location Details
Second line of radio buttons still has weird indent (can be seen after choosing “Discriminated against in a commercial location or public place” under “Place of worship”
![Screen Shot 2020-06-23 at 4.11.13 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/1103e7c7-c2e2-4f21-a00d-83cca838ce3d)

### This is also an issue on desktop
32px spacing is needed between Card header and question still (same issue on desktop)
![Screen Shot 2020-06-23 at 4.12.11 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/73989015-9947-4d2d-86ed-51960cd11781)

## 9. Review
- **Spacing:** Looks like these cards maybe aren’t using the 24px at top?
- **Edit buttons** Should follow the same 24px padding on either side, this looks wider than the rest of the content
![Screen Shot 2020-06-23 at 4.18.52 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/f4a17fd6-79ab-4a99-b6a0-d9c86ca3bb11)

## 10. Privacy Policy footer
Same issue as others, text should use the full width of the columns on mobile
![Screen Shot 2020-06-23 at 4.23.39 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/79c92ba4-a642-436a-a704-57a34fb5ba8e)

## 11. Confirmation
- Same as previous issues, can the “Please save your record number..” context have the same 24px padding instead of being indented and uneven? I see it’s trying to align with the “Report successfully submitted” but it looks off.
- Checkmark should align with the first line of the header, not the center
- Padding above/below only needs to be 24px (looks bigger)
- Top two corners of blue should be rounded

![Screen Shot 2020-06-23 at 4.21.14 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/b706ae27-1e49-41be-9db6-6e68d9fa2693)
![Screen Shot 2020-06-23 at 4.22.11 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c678c122-b1d7-4e12-9747-86c48074a71c)

**Comment by cantsin** [comment]
Note: this is assigned to Matt who isn't in Zenhub yet (leaving assignee list empty, apologies in advance if this is confusing)

**Comment by Jacklynn** [comment]
I checked in with Aviva about the line color on mo bile and they should be `grey-cool-10` `#DFE1E2`. She said this should be the same as the lines on the review/confirmation page, if they're not.

**Comment by Jacklynn** [comment]
Er, correction, the review page is supposed to have a gray line when it looks like this. I'd have to check on the confirmation page. ![Screen Shot 2020-07-23 at 8.57.33 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/507fe8a2-a77c-4286-a1d5-d1f1e285b2f0)

**Comment by cantsin** [comment]
During review, I noticed that the landing page "protected by civil rights laws" sidebar on tablet doesn't look great:

![2020-07-24_10-05.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/fcdcd216-7513-4662-9c87-e11af222aafa)

@Jacklynn what do you think? should we add this as an extra task to this issue or create a new issue?

**Comment by Jacklynn** [comment]
@cantsin I saw your comment about the tablet view but I can't find it now...It would be really great to get at least some padding in for the so the line isn't running into the text. Is that possible for the release?

But looking at @AvivaOskow mocks she actually proposed that they stack on tablet. Would this be possible or a longer term effort?
![Screen Shot 2020-07-24 at 11.00.58 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/fdcf6d90-e306-4bb3-93ce-9c39c12f7db9)

**Comment by cantsin** [comment]
@Jacklynn I deleted the tablet issue as I realized it was caused directly by changes in the PR.

Stacking is possible, but I defer to @MattBowles8 as to whether or not he wants to take this on. His PR is already getting a bit large...

**Comment by blaughman** [comment]
Deployed to Prod on 8/18/20.
