### ISSUE TITLE
Retire Classification Checklist

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#883]
- [ ] Meet with Amanda/Carolyn
- [ ] Connect with Killian – Make sure we meet Privacy and Records Retention requirements and that our system is documented as the system of record for those items.
- [ ] Loop in Sean Cononie
- [ ] Meet with Meghan Fiebelkorn in CAO
- [ ] Carolyn to provide complete data to Lindsay (with CAO)

**Comment by LindsayYoung** [comment]
Update on the CAO system from the meeting 2/26 (Suey, Gary, Robert)

- It looks like CAO can use ICM for DJ number generation for now, eventually it should be in the CAO's billing tool (They have their own outside of ICM)
- They are still trying to pin down the retention schedule
- CAO's Classification records should not be migrated into the portal

**Comment by blaughman** [comment]
I reached out to Doug York, Records Manager for CRT.  Per Suey's instructions, he is to work with ORMP to ensure we are properly decommissioning the system from a records retention perspective.

**Comment by blaughman** [comment]
Blocked by Records Unit's efforts to satisfy ORMP requirements.
